# Python Django
# Test a Django project on multiple versions of Python.
# https://aka.ms/yaml

phases:

- phase: 'Test'
  queue:
    name: 'Hosted Linux Preview'
    parallel: 3
    matrix:
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
      Python37-dev:
        PYTHON_VERSION: '>= 3.7.0a'
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install dependencies'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: pip install unittest-xml-reporting
    displayName: 'Install unittest-xml-reporting'

  - script: python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/TEST-*.xml"
      testRunTitle: 'Python $(PYTHON_VERSION)'

# Phase 3: Copy sources to prepare for publishing
- phase: 'PublishProjectArtifact'
  dependsOn:
    - 'Test'
  variables:
    projectRoot: '.'
  queue: 'Hosted Linux Preview'
  steps:
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/$(projectRoot)'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'artifact'
      publishLocation: 'container'
